### ISSUE TITLE
Add "Help -> About" menu

### ISSUE THREAD

**Issue by staabm** [manojVivek/responsively-app#120]
primary driver: there is no way I can see in which version the app is currently installed ?

possible additional infos in this menu could be
- version of the app
- link to the website
- link to the github repo
- link to the docs
- credits for the author

**Comment by DamnedScholar** [comment]
The diversity of webapps is such that getting one piece of information (version) across a majority of users would require the ability to read `package.json`, `pyproject.toml`, PHP config files for major platforms (Wordpress, Laravel, CodeIgniter, MediaWiki), Java manifests, git tags, and maybe other things. Since there is so much that has to be collected, I don't think it makes sense to hardcode what people can see. Node makes it easy to run interpreters for many files and collate the data into a common interface to feed to the display, and anyone who writes this functionality would have to go through all the steps to get the data in the first place, so I think it makes sense to put all of the data in all of those files into the user's hands instead of just coming up with a list of what you expect them to see. The browser side of Electron makes it easy to display information selectively and I think it would make the most sense for a feature like this to fish for *literally everything* under its scope (with a directory of individual interpreter modules that get added to constantly as open source evolves) and store a set of preferred fields (with reasonable defaults, but a UI that shows you immediately that you can change them) to show the most important information on one view and then everything imaginable in the next one.

In thinking about this, I see a few side benefits beyond configuration. If @manojVivek feels like it's appropriate for Responsively to be hands-on about how it presents information, the app could even compare the different files and warn of things like version number mismatches (which could be intentional or mistakes) or when important fields are left blank. If the display is configured for such, one could bring up a well-styled breakdown of dozens of pieces of information from multiple sources for a complex app. I've just gotten started looking at this project, but that kind of broad-spectrum comparison seems like an appropriate feature stretch that would be broadly used if designed well.

**Comment by staabm** [comment]
Thanks for getting back to me.

> The diversity of webapps is such that getting one piece of information (version) across a majority of users would require the ability to read package.json, pyproject.toml, PHP config files for major platforms (Wordpress, Laravel, CodeIgniter, MediaWiki), Java manifests, git tags, and maybe other things. Since there is so much that has to be collected, I don't think it makes sense to hardcode what people can see. Node makes it easy to run interpreters for many files and collate the data into a common interface to feed to the display, and anyone who writes this functionality would have to go through all the steps to get the data in the first place, so I think it makes sense to put all of the data in all of those files into the user's hands instead of just coming up with a list of what you expect them to see. The browser side of Electron makes it easy to display information selectively and I think it would make the most sense for a feature like this to fish for literally everything under its scope (with a directory of individual interpreter modules that get added to constantly as open source evolves) and store a set of preferred fields (with reasonable defaults, but a UI that shows you immediately that you can change them) to show the most important information on one view and then everything imaginable in the next one.

Hmm .. my primary intension was just to have a „about dialog“ in the menu - like 95% of desktop applications have.. this dialog would show me the version of the responsive-app I have installed, so I can e.g. check against the websites whether updates are available or I can show the versionnwhen reporting problems.

Not sure how this relates to all the points you mentioned in the comment...

> In thinking about this, I see a few side benefits beyond configuration. If @manojVivek feels like it's appropriate for Responsively to be hands-on about how it presents information, the app could even compare the different files and warn of things like version number mismatches (which could be intentional or mistakes) or when important fields are left blank. If the display is configured for such, one could bring up a well-styled breakdown of dozens of pieces of information from multiple sources for a complex app. I've just gotten started looking at this project, but that kind of broad-spectrum comparison seems like an appropriate feature stretch that would be broadly used if designed well.

This sounds like a totally different problem/issue and should be discussed in a separate issue - not here

**Comment by manojVivek** [comment]
@DamnedScholar I agree, we should show as much info as possible. Though the vision that you shared can be more like a long-term goal. I see the PR by @jjavierdguezas is a good first step in that direction. 🙂

**Comment by manojVivek** [comment]
This one is going live in v0.1.6 tonight.
