### ISSUE TITLE
v0.1.6 crashs on startup

### ISSUE THREAD

**Issue by duongle26** [manojVivek/responsively-app#150]
![image](https://user-images.githubusercontent.com/28813618/83361313-1cbee480-a3b2-11ea-8d86-332e526da5a8.png)
```
{
    hasError: true,
    error: {},
    errorInfo: {
      componentStack:
        '\n in Unknown (created by ConnectFunction)\n in ConnectFunction\n in div\n in L_ (created by ConnectFunction)\n in ConnectFunction (created by Context.Consumer)\n in Route\n in Switch\n in div\n in div\n in B\n in ip\n in Router (created by r)\n in r (created by Context.Consumer)\n in n (created by ConnectFunction)\n in ConnectFunction\n in wd\n in up\n in Provider\n in fp\n in AppContainer'
    }
}
```

**Comment by manojVivek** [comment]
@duongle26 Can you let me know the OS in which this is happening?

**Comment by manojVivek** [comment]
This is because of the schema change that went in with the v0.1.6. It was affecting the users who had custom devices added previously. 

@duongle26  I have updated v.0.1.6 with a fix for handling the crash scenario. Can you please check with the latest binary here - https://github.com/manojVivek/responsively-app/releases

**Comment by duongle26** [comment]
> This is because of the schema change that went in with the v0.1.6. It was affecting the users who had custom devices added previously.
> 
> @duongle26 I have updated v.0.1.6 with a fix for handling the crash scenario. Can you please check with the latest binary here - https://github.com/manojVivek/responsively-app/releases

Thanks for your update. It's working fine now.
