### ISSUE TITLE
Add options to emulate OS dark/light mode settings

### ISSUE THREAD

**Issue by manojVivek** [manojVivek/responsively-app#165]
Webpages can styling depending on the user's operating system's dark and light mode appearance settings. 

Add an option to set the display mode for the rendered devices.

**Comment by AARYAN-MAHENDRA** [comment]
can I work on this issue.Actually its my first time so please guide me through it

**Comment by RomainFrancony** [comment]
I found a way to do it using Electron [nativeTheme API](https://www.electronjs.org/docs/api/native-theme#nativethemethemesource).

Here is a [video](https://drive.google.com/file/d/1rPlqVG2QmSqRXWHyAFZeHDVzw9ce1cPc/view?usp=sharing) of the current implementation.

I implemented 3 options:
- `system`: uses the operating system preference
- `light`: equivalent of `prefers-color-scheme: light`
- `dark`: equivalent of `prefers-color-scheme: dark`

The setting is not remembered when the app is closed since I did not find any use case where it was useful.

Now there is only one small problem, since I'm changing the native theme setting of Electron, that means the app itself switch to light/dark mode, so the right click menu and select are now rendered in dark mode when the setting is set to dark.
I personally don't think this is a huge problem and we can keep it that way.

Also the current icon for the system option is not really meaningful, if you have a better idea.



Also I'm sorry @AARYAN-MAHENDRA, I kinda stole it from you 😅

**Comment by AARYAN-MAHENDRA** [comment]
Its totally okay.I just started working on it today.

**Comment by manojVivek** [comment]
@RomainFrancony You nailed it there!  🚀 

I think it is ok that the app itself switches to light/dark mode. 👍 

**Quick suggestion regarding the icon behavior**: 
To keep it simple, we can just keep the toolbar icon to switch between `dark` and `light` mode and remove the `system` option. 
From a user perspective, when developing a page we would either want to test it in `light` or `dark` mode. Also `system` mode is going to be practical of less use, as the users are not going to change the system preferences in order to see how the page behaves.

Maybe when the app starts, the initial value can be initialized from what is in the system settings. This way we can eliminate the little menu and the icon can just act as a switch. 

What do you think?

**Comment by RomainFrancony** [comment]
@manojVivek that sounds good to me 👍 

I will do the change and make a pull request in the next ~24h
