### ISSUE TITLE
DevTools first row disappears when it is open and you go to customize devices 

### ISSUE THREAD

**Issue by jjavierdguezas** [manojVivek/responsively-app#257]
>Version: 0.5.0
Electron: 8.3.0
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Windows_NT x64 10.0.18362

If you have the dev tools open and you go to customize devices, the dev tools remains there but the first row disappears, so we cannot close it
![dev_tools](https://user-images.githubusercontent.com/13673443/86458666-e6181900-bd25-11ea-8c01-466881500cf5.gif)

**Comment by manojVivek** [comment]
Yeah, it is because of the way the docked dev-tools functionality is implemented. The first row is a `div` in the main window while the actual `devtools` section is a `BrowserView`. It is made to feel like it is one section but actually it is not. 😁  

This is done in such a way because of a disability in electron that was preventing the `devtools` content to be loaded as a `webview`.

Here the overlay from the Device manager is hiding the top row `div`, maybe increasing the `z-index` might help?
