### ISSUE TITLE
Responsive Mode dimensions are in the wrong order

### ISSUE THREAD

**Issue by stevedesmond-ca** [manojVivek/responsively-app#295]
Steps to reproduce:
- launch Responsively v0.6.1
- resize "Responsive Mode" to 800px wide by 600px tall

Expected result:
- dimensions show as "800x600"

Observed result:
- dimensions show as "600x800"

![image](https://user-images.githubusercontent.com/195896/86948040-9e750100-c11a-11ea-8484-e857441f3766.png)

**Comment by jjavierdguezas** [comment]
The issue here is with the `Tilt Device` button which is not working with this special device
In the image shared by @stevedesmond-ca it can be seen that the button was pressed, tso the dimension shows HxW instead of WxH
When the button is not pressed the info displayed is valid
When the button is pressed the info flips but not the view, it also seems that this action is not allowed for this device (the button looks gray as if it was disabled) but the click does something

![resp2](https://user-images.githubusercontent.com/13673443/86949601-32f95680-c14f-11ea-8ab1-28ea0e316093.gif)

cc: @manojVivek

**Comment by stevedesmond-ca** [comment]
Thanks for the clarification, indeed the "half-working but appearing disabled" icon was not obvious!

**Comment by manojVivek** [comment]
Even the re-sizable device should be allowed for rotation, I guess.

@kvnam Thoughts?

**Comment by kvnam** [comment]
@manojVivek @jjavierdguezas I agree, the rotation should work for this mode as well. Will get this in with the other fixes as well. Thanks guys!
